name: build-ffmpeg-linux

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day at 00:00

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zerocluster/node
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HOME: /root
      MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
      CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
    steps:
      - uses: softvisio/actions/checkout@v1

      - run: |
          npm install --ignore-scripts
          npm run build-ffmpeg-linux
